#!/usr/bin/env python3
"""
E. Training Pipeline for Two-Stage Face Recognition

This script trains both Stage A and Stage B models:
1. Stage A: Person vs No-Person (Binary)
2. Stage B: 5 Known Persons (Multi-class)

Features:
- Early stopping and learning rate reduction
- Class weighting for imbalanced data
- Confusion matrix and accuracy metrics
- Model checkpointing

Usage:
    python E_train_model.py --data_dir processed --epochs 100
"""

import os
import json
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import callbacks
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
from pathlib import Path
import argparse
from typing import Tuple, Dict, List

# Import model architectures
from D_model_architecture import (
    create_stage_a_model, 
    create_stage_b_model,
    print_model_analysis
)

# =============================================================================
# Configuration
# =============================================================================
BATCH_SIZE = 32
EPOCHS = 150
LEARNING_RATE = 0.0005
EARLY_STOPPING_PATIENCE = 25
LR_REDUCE_PATIENCE = 12
LR_REDUCE_FACTOR = 0.5
MIN_LR = 1e-6


# =============================================================================
# Data Loading
# =============================================================================
def load_data(data_dir: str, stage: str) -> Dict[str, Tuple[np.ndarray, np.ndarray]]:
    """
    Load preprocessed data for a specific stage.
    
    Args:
        data_dir: Directory with processed NPZ files
        stage: 'a' for Stage A, 'b' for Stage B
        
    Returns:
        Dictionary with 'train', 'val', 'test' tuples
    """
    data_path = Path(data_dir)
    
    prefix = f'stage_{stage}'
    
    train_data = np.load(data_path / f'{prefix}_train.npz')
    val_data = np.load(data_path / f'{prefix}_val.npz')
    test_data = np.load(data_path / f'{prefix}_test.npz')
    
    return {
        'train': (train_data['X'], train_data['y']),
        'val': (val_data['X'], val_data['y']),
        'test': (test_data['X'], test_data['y'])
    }


def compute_class_weights(y: np.ndarray) -> Dict[int, float]:
    """
    Compute class weights for imbalanced datasets using squared inverse
    frequency weighting, capped at 10x to avoid training instability.

    Args:
        y: Array of class labels

    Returns:
        Dictionary mapping class index to weight
    """
    classes = np.unique(y)
    counts = {cls: int(np.sum(y == cls)) for cls in classes}
    max_count = max(counts.values())

    weights = {}
    for cls in classes:
        raw_weight = (max_count / counts[cls]) ** 1.5
        weights[cls] = min(raw_weight, 10.0)

    return weights


def augment_minority_classes(X_train: np.ndarray, y_train: np.ndarray,
                             target_ratio: float = 0.85) -> Tuple[np.ndarray, np.ndarray]:
    """
    Oversample minority classes using data augmentation to partially
    balance the training set.

    Each minority class is augmented until it reaches target_ratio * max_class_count.
    Augmented images are generated by the same Augmentor used during preprocessing.

    Args:
        X_train: Training images of shape (N, H, W, 1)
        y_train: Training labels
        target_ratio: Minority classes are grown to this fraction of the majority count

    Returns:
        Balanced (X, y) arrays with minority classes oversampled
    """
    from C_preprocess_and_augment import Augmentor

    classes, counts = np.unique(y_train, return_counts=True)
    max_count = int(np.max(counts))
    target_count = int(max_count * target_ratio)

    print(f"\n=== Oversampling Minority Classes ===")
    print(f"  Target count per class: {target_count}")

    augmentor = Augmentor(seed=42)
    X_aug_list = [X_train]
    y_aug_list = [y_train]

    for cls, count in zip(classes, counts):
        if count < target_count:
            needed = target_count - count
            cls_images = X_train[y_train == cls]
            aug_X = []
            aug_y = []
            rng = np.random.default_rng(seed=42 + int(cls))

            while len(aug_X) < needed:
                idx = rng.integers(0, len(cls_images))
                img_2d = cls_images[idx].squeeze()  # (H, W)
                aug_versions = augmentor.augment(img_2d, num_augmentations=4)[1:]
                for aug_img in aug_versions:
                    if len(aug_X) >= needed:
                        break
                    aug_X.append(aug_img.reshape(96, 96, 1))
                    aug_y.append(cls)

            X_aug_list.append(np.array(aug_X))
            y_aug_list.append(np.array(aug_y))
            print(f"  Class {cls}: {count} → {count + len(aug_X)} samples (+{len(aug_X)})")
        else:
            print(f"  Class {cls}: {count} (no oversampling needed)")

    X_balanced = np.concatenate(X_aug_list, axis=0)
    y_balanced = np.concatenate(y_aug_list, axis=0)

    # Shuffle to mix augmented and original samples
    indices = np.random.default_rng(seed=0).permutation(len(X_balanced))
    return X_balanced[indices], y_balanced[indices]


# =============================================================================
# Callbacks
# =============================================================================
def create_callbacks(model_name: str, 
                     output_dir: str) -> List[callbacks.Callback]:
    """
    Create training callbacks.
    
    Args:
        model_name: Name for saving checkpoints
        output_dir: Directory to save models
        
    Returns:
        List of Keras callbacks
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    callback_list = [
        # Model checkpoint - save best model
        callbacks.ModelCheckpoint(
            filepath=str(output_path / f'{model_name}_best.keras'),
            monitor='val_accuracy',
            mode='max',
            save_best_only=True,
            verbose=1
        ),
        
        # Early stopping
        callbacks.EarlyStopping(
            monitor='val_accuracy',
            patience=EARLY_STOPPING_PATIENCE,
            mode='max',
            restore_best_weights=True,
            verbose=1
        ),
        
        # Reduce learning rate on plateau
        callbacks.ReduceLROnPlateau(
            monitor='val_loss',
            factor=LR_REDUCE_FACTOR,
            patience=LR_REDUCE_PATIENCE,
            min_lr=MIN_LR,
            verbose=1
        ),
        
        # TensorBoard logging
        callbacks.TensorBoard(
            log_dir=str(output_path / 'logs' / model_name),
            histogram_freq=0,
            write_graph=True
        )
    ]
    
    return callback_list


# =============================================================================
# Training Functions
# =============================================================================
def train_model(model: keras.Model,
                train_data: Tuple[np.ndarray, np.ndarray],
                val_data: Tuple[np.ndarray, np.ndarray],
                model_name: str,
                output_dir: str,
                epochs: int = EPOCHS,
                batch_size: int = BATCH_SIZE,
                use_class_weights: bool = True) -> keras.callbacks.History:
    """
    Train a model with the given data.
    
    Args:
        model: Keras model to train
        train_data: (X_train, y_train) tuple
        val_data: (X_val, y_val) tuple
        model_name: Name for saving
        output_dir: Output directory
        epochs: Number of epochs
        batch_size: Batch size
        use_class_weights: Whether to use class weighting
        
    Returns:
        Training history
    """
    X_train, y_train = train_data
    X_val, y_val = val_data
    
    # Compile model
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=LEARNING_RATE),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    
    # Compute class weights
    class_weights = None
    if use_class_weights:
        class_weights = compute_class_weights(y_train)
        print(f"\nClass weights: {class_weights}")
    
    # Create callbacks
    callback_list = create_callbacks(model_name, output_dir)
    
    # Print training info
    print(f"\n{'='*60}")
    print(f"Training {model_name}")
    print(f"{'='*60}")
    print(f"Training samples: {len(X_train)}")
    print(f"Validation samples: {len(X_val)}")
    print(f"Batch size: {batch_size}")
    print(f"Max epochs: {epochs}")
    
    # Train
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size,
        class_weight=class_weights,
        callbacks=callback_list,
        verbose=1
    )
    
    return history


# =============================================================================
# Evaluation Functions
# =============================================================================
def evaluate_model(model: keras.Model,
                   test_data: Tuple[np.ndarray, np.ndarray],
                   class_names: List[str],
                   model_name: str,
                   output_dir: str):
    """
    Evaluate model on test data and generate reports.
    
    Args:
        model: Trained Keras model
        test_data: (X_test, y_test) tuple
        class_names: List of class names
        model_name: Model name for saving
        output_dir: Output directory
    """
    X_test, y_test = test_data
    
    # Get predictions
    y_pred_probs = model.predict(X_test, verbose=0)
    y_pred = np.argmax(y_pred_probs, axis=1)
    
    # Calculate accuracy
    accuracy = np.mean(y_pred == y_test)
    
    print(f"\n{'='*60}")
    print(f"Evaluation Results: {model_name}")
    print(f"{'='*60}")
    print(f"Test Accuracy: {accuracy*100:.2f}%")
    
    # Classification report
    print(f"\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=class_names))
    
    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    print(f"\nConfusion Matrix:")
    print(cm)
    
    # Save confusion matrix plot
    output_path = Path(output_dir)
    plot_confusion_matrix(cm, class_names, 
                          str(output_path / f'{model_name}_confusion_matrix.png'))
    
    # Save metrics to JSON
    metrics = {
        'model_name': model_name,
        'test_accuracy': float(accuracy),
        'confusion_matrix': cm.tolist(),
        'class_names': class_names
    }
    
    with open(output_path / f'{model_name}_metrics.json', 'w') as f:
        json.dump(metrics, f, indent=2)
    
    return accuracy, cm


def plot_confusion_matrix(cm: np.ndarray, 
                          class_names: List[str],
                          save_path: str):
    """Plot and save confusion matrix."""
    fig, ax = plt.subplots(figsize=(8, 6))
    
    im = ax.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
    ax.figure.colorbar(im, ax=ax)
    
    ax.set(xticks=np.arange(cm.shape[1]),
           yticks=np.arange(cm.shape[0]),
           xticklabels=class_names,
           yticklabels=class_names,
           title='Confusion Matrix',
           ylabel='True label',
           xlabel='Predicted label')
    
    plt.setp(ax.get_xticklabels(), rotation=45, ha="right",
             rotation_mode="anchor")
    
    # Add text annotations
    thresh = cm.max() / 2.
    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            ax.text(j, i, format(cm[i, j], 'd'),
                    ha="center", va="center",
                    color="white" if cm[i, j] > thresh else "black")
    
    fig.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()
    print(f"Confusion matrix saved to: {save_path}")


def plot_training_history(history: keras.callbacks.History,
                          model_name: str,
                          save_path: str):
    """Plot training history (accuracy and loss)."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    
    # Accuracy plot
    axes[0].plot(history.history['accuracy'], label='Train')
    axes[0].plot(history.history['val_accuracy'], label='Validation')
    axes[0].set_title(f'{model_name} - Accuracy')
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Accuracy')
    axes[0].legend()
    axes[0].grid(True)
    
    # Loss plot
    axes[1].plot(history.history['loss'], label='Train')
    axes[1].plot(history.history['val_loss'], label='Validation')
    axes[1].set_title(f'{model_name} - Loss')
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Loss')
    axes[1].legend()
    axes[1].grid(True)
    
    fig.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()
    print(f"Training history saved to: {save_path}")


# =============================================================================
# Unknown Threshold Tuning
# =============================================================================
def tune_unknown_threshold(model: keras.Model,
                           unknown_data: np.ndarray,
                           known_test_data: Tuple[np.ndarray, np.ndarray],
                           class_names: List[str],
                           output_dir: str) -> float:
    """
    Tune the confidence threshold for unknown person detection.
    
    The goal is to find a threshold that:
    - Correctly rejects unknown persons (high specificity for unknown)
    - Maintains high accuracy on known persons
    
    Args:
        model: Trained Stage B model
        unknown_data: Images of unknown persons
        known_test_data: (X, y) of known persons
        class_names: List of known class names
        output_dir: Output directory
        
    Returns:
        Optimal threshold value
    """
    print(f"\n{'='*60}")
    print("Tuning Unknown Detection Threshold")
    print(f"{'='*60}")
    
    if len(unknown_data) == 0:
        print("No unknown test data available. Using default threshold: 0.70")
        return 0.70
    
    X_known, y_known = known_test_data
    
    # Get predictions for known and unknown
    known_probs = model.predict(X_known, verbose=0)
    unknown_probs = model.predict(unknown_data, verbose=0)
    
    known_max_conf = np.max(known_probs, axis=1)
    unknown_max_conf = np.max(unknown_probs, axis=1)
    
    # Test different thresholds
    thresholds = np.arange(0.50, 0.95, 0.05)
    results = []
    
    print(f"\n{'Threshold':>10} | {'Known Acc':>10} | {'Unknown Rej':>12} | {'Combined':>10}")
    print("-" * 50)
    
    for thresh in thresholds:
        # For known: accuracy on correctly classified with confidence >= threshold
        known_preds = np.argmax(known_probs, axis=1)
        known_mask = known_max_conf >= thresh
        
        if np.sum(known_mask) > 0:
            known_correct = np.sum((known_preds == y_known) & known_mask)
            known_total = np.sum(known_mask)
            known_acc = known_correct / known_total
        else:
            known_acc = 0
        
        # For unknown: rejection rate (correctly identified as unknown)
        unknown_rejected = np.sum(unknown_max_conf < thresh)
        unknown_rej = unknown_rejected / len(unknown_max_conf)
        
        # Combined score (F1-like balance)
        combined = 2 * (known_acc * unknown_rej) / (known_acc + unknown_rej + 1e-10)
        
        results.append({
            'threshold': thresh,
            'known_accuracy': known_acc,
            'unknown_rejection': unknown_rej,
            'combined_score': combined
        })
        
        print(f"{thresh:>10.2f} | {known_acc:>10.2%} | {unknown_rej:>12.2%} | {combined:>10.2%}")
    
    # Find best threshold
    best = max(results, key=lambda x: x['combined_score'])
    
    print(f"\nOptimal threshold: {best['threshold']:.2f}")
    print(f"  Known accuracy: {best['known_accuracy']:.2%}")
    print(f"  Unknown rejection: {best['unknown_rejection']:.2%}")
    
    # Save threshold tuning results
    output_path = Path(output_dir)
    with open(output_path / 'threshold_tuning.json', 'w') as f:
        json.dump({
            'optimal_threshold': best['threshold'],
            'known_accuracy': best['known_accuracy'],
            'unknown_rejection': best['unknown_rejection'],
            'all_results': results
        }, f, indent=2)
    
    return best['threshold']


# =============================================================================
# Main Training Pipeline
# =============================================================================
def main():
    parser = argparse.ArgumentParser(description='Train face recognition models')
    parser.add_argument('--data_dir', type=str, default='processed',
                        help='Directory with preprocessed data')
    parser.add_argument('--output_dir', type=str, default='models',
                        help='Directory to save trained models')
    parser.add_argument('--epochs', type=int, default=EPOCHS,
                        help='Maximum training epochs')
    parser.add_argument('--batch_size', type=int, default=BATCH_SIZE,
                        help='Training batch size')
    parser.add_argument('--train_stage', type=str, default='both',
                        choices=['a', 'b', 'both'],
                        help='Which stage to train')
    args = parser.parse_args()
    
    # Set random seeds
    np.random.seed(42)
    tf.random.set_seed(42)
    
    # Load metadata
    data_path = Path(args.data_dir)
    with open(data_path / 'metadata.json', 'r') as f:
        metadata = json.load(f)
    
    print("=" * 60)
    print("TinyML Face Recognition Training Pipeline")
    print("=" * 60)
    print(f"\nData directory: {args.data_dir}")
    print(f"Output directory: {args.output_dir}")
    print(f"Image size: {metadata['img_size']}x{metadata['img_size']}")
    
    output_path = Path(args.output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # =================================
    # Stage A: Person Detection
    # =================================
    if args.train_stage in ['a', 'both']:
        print("\n" + "=" * 60)
        print("STAGE A: Person Detection Training")
        print("=" * 60)
        
        # Load Stage A data
        stage_a_data = load_data(args.data_dir, 'a')
        class_names_a = metadata['class_names_stage_a']
        
        print(f"\nClasses: {class_names_a}")
        print(f"Train: {len(stage_a_data['train'][0])}")
        print(f"Val: {len(stage_a_data['val'][0])}")
        print(f"Test: {len(stage_a_data['test'][0])}")
        
        # Create and train model
        model_a = create_stage_a_model()
        print_model_analysis(model_a)
        
        history_a = train_model(
            model_a,
            stage_a_data['train'],
            stage_a_data['val'],
            'stage_a',
            args.output_dir,
            epochs=args.epochs,
            batch_size=args.batch_size
        )
        
        # Plot training history
        plot_training_history(history_a, 'Stage A',
                              str(output_path / 'stage_a_history.png'))
        
        # Evaluate
        acc_a, cm_a = evaluate_model(
            model_a,
            stage_a_data['test'],
            class_names_a,
            'stage_a',
            args.output_dir
        )
        
        # Save final model
        model_a.save(output_path / 'stage_a_final.keras')
        print(f"\nStage A model saved to: {output_path / 'stage_a_final.keras'}")
    
    # =================================
    # Stage B: Face Recognition
    # =================================
    if args.train_stage in ['b', 'both']:
        print("\n" + "=" * 60)
        print("STAGE B: Face Recognition Training")
        print("=" * 60)
        
        # Load Stage B data
        stage_b_data = load_data(args.data_dir, 'b')
        class_names_b = metadata['class_names_stage_b']
        num_classes = len(class_names_b)
        
        print(f"\nClasses: {class_names_b}")
        print(f"Number of classes: {num_classes}")
        print(f"Train: {len(stage_b_data['train'][0])}")
        print(f"Val: {len(stage_b_data['val'][0])}")
        print(f"Test: {len(stage_b_data['test'][0])}")
        
        # Oversample minority classes before training
        X_train_b, y_train_b = augment_minority_classes(
            stage_b_data['train'][0],
            stage_b_data['train'][1],
            target_ratio=0.85
        )
        stage_b_data['train'] = (X_train_b, y_train_b)
        print(f"\nBalanced training set: {len(X_train_b)} samples")

        # Create and train model
        model_b = create_stage_b_model(num_classes=num_classes)
        print_model_analysis(model_b)

        history_b = train_model(
            model_b,
            stage_b_data['train'],
            stage_b_data['val'],
            'stage_b',
            args.output_dir,
            epochs=args.epochs,
            batch_size=args.batch_size
        )
        
        # Plot training history
        plot_training_history(history_b, 'Stage B',
                              str(output_path / 'stage_b_history.png'))
        
        # Evaluate
        acc_b, cm_b = evaluate_model(
            model_b,
            stage_b_data['test'],
            class_names_b,
            'stage_b',
            args.output_dir
        )
        
        # Tune unknown threshold
        unknown_path = data_path / 'unknown_test.npz'
        if unknown_path.exists():
            unknown_data = np.load(unknown_path)['X']
            threshold = tune_unknown_threshold(
                model_b,
                unknown_data,
                stage_b_data['test'],
                class_names_b,
                args.output_dir
            )
            
            # Update metadata with threshold
            metadata['unknown_threshold'] = threshold
        else:
            print("\nNo unknown test data found. Using default threshold: 0.70")
            metadata['unknown_threshold'] = 0.70
        
        # Save final model
        model_b.save(output_path / 'stage_b_final.keras')
        print(f"\nStage B model saved to: {output_path / 'stage_b_final.keras'}")
    
    # Save updated metadata
    with open(output_path / 'training_metadata.json', 'w') as f:
        json.dump(metadata, f, indent=2)
    
    print("\n" + "=" * 60)
    print("Training Complete!")
    print("=" * 60)
    print(f"\nNext steps:")
    print(f"  1. Convert to TFLite: python F_quantize_model.py --model_dir {args.output_dir}")
    print(f"  2. Deploy to Arduino: See G_arduino_firmware.ino")


if __name__ == '__main__':
    main()
